# Makefile for elcScriptedGrader
#
# @author  Michael E. Cotterell <mepcotterell@gmail.com>
# @license LICENSE (MIT style license file).
#
# EDIT THIS FILE TO BE PROJECT SPECIFIC!
#

all: compile test

compile:

test:

clean: